W0909 08:05:49.237000 2526692 torch/distributed/run.py:774] 
W0909 08:05:49.237000 2526692 torch/distributed/run.py:774] *****************************************
W0909 08:05:49.237000 2526692 torch/distributed/run.py:774] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0909 08:05:49.237000 2526692 torch/distributed/run.py:774] *****************************************
[Rank 5] 分布式进程组初始化完成，绑定设备: cuda:5
[Rank 7] 分布式进程组初始化完成，绑定设备: cuda:7
[Rank 6] 分布式进程组初始化完成，绑定设备: cuda:6
量化流程执行失败: 'LoadProcessor' object has no attribute 'model_path'
量化流程执行失败: 'LoadProcessor' object has no attribute 'model_path'
量化流程执行失败: 'LoadProcessor' object has no attribute 'model_path'
[Rank 4] 分布式进程组初始化完成，绑定设备: cuda:4
[rank5]: Traceback (most recent call last):
[rank5]:   File "/data00/tjx/quant/test.py", line 53, in <module>
[rank5]:     main()
[rank5]:   File "/data00/tjx/quant/test.py", line 42, in main
[rank5]:     quant_service.run_pipeline(
[rank5]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 74, in run_pipeline
[rank5]:     self.processors["load"].process(** load_params)
[rank5]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 113, in process
[rank5]:     self.pre_process(model_path, quant_config_path)
[rank5]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 158, in pre_process
[rank5]:     self._parse_model_config(model_path)
[rank5]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 144, in _parse_model_config
[rank5]:     original_config_path = os.path.join(self.model_path, "config.json")
[rank5]:                                         ^^^^^^^^^^^^^^^
[rank5]: AttributeError: 'LoadProcessor' object has no attribute 'model_path'
[rank7]: Traceback (most recent call last):
[rank7]:   File "/data00/tjx/quant/test.py", line 53, in <module>
[rank7]:     main()
[rank7]:   File "/data00/tjx/quant/test.py", line 42, in main
[rank7]:     quant_service.run_pipeline(
[rank7]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 74, in run_pipeline
[rank7]:     self.processors["load"].process(** load_params)
[rank7]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 113, in process
[rank7]:     self.pre_process(model_path, quant_config_path)
[rank7]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 158, in pre_process
[rank7]:     self._parse_model_config(model_path)
[rank7]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 144, in _parse_model_config
[rank7]:     original_config_path = os.path.join(self.model_path, "config.json")
[rank7]:                                         ^^^^^^^^^^^^^^^
[rank7]: AttributeError: 'LoadProcessor' object has no attribute 'model_path'
量化流程执行失败: 'LoadProcessor' object has no attribute 'model_path'
[rank6]: Traceback (most recent call last):
[rank6]:   File "/data00/tjx/quant/test.py", line 53, in <module>
[rank6]:     main()
[rank6]:   File "/data00/tjx/quant/test.py", line 42, in main
[rank6]:     quant_service.run_pipeline(
[rank6]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 74, in run_pipeline
[rank6]:     self.processors["load"].process(** load_params)
[rank6]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 113, in process
[rank6]:     self.pre_process(model_path, quant_config_path)
[rank6]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 158, in pre_process
[rank6]:     self._parse_model_config(model_path)
[rank6]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 144, in _parse_model_config
[rank6]:     original_config_path = os.path.join(self.model_path, "config.json")
[rank6]:                                         ^^^^^^^^^^^^^^^
[rank6]: AttributeError: 'LoadProcessor' object has no attribute 'model_path'
[rank4]: Traceback (most recent call last):
[rank4]:   File "/data00/tjx/quant/test.py", line 53, in <module>
[rank4]:     main()
[rank4]:   File "/data00/tjx/quant/test.py", line 42, in main
[rank4]:     quant_service.run_pipeline(
[rank4]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 74, in run_pipeline
[rank4]:     self.processors["load"].process(** load_params)
[rank4]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 113, in process
[rank4]:     self.pre_process(model_path, quant_config_path)
[rank4]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 158, in pre_process
[rank4]:     self._parse_model_config(model_path)
[rank4]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 144, in _parse_model_config
[rank4]:     original_config_path = os.path.join(self.model_path, "config.json")
[rank4]:                                         ^^^^^^^^^^^^^^^
[rank4]: AttributeError: 'LoadProcessor' object has no attribute 'model_path'
[Rank 0] 分布式进程组初始化完成，绑定设备: cuda:0
执行步骤: load（所有进程同时执行）
量化流程执行失败: 'LoadProcessor' object has no attribute 'model_path'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data00/tjx/quant/test.py", line 53, in <module>
[rank0]:     main()
[rank0]:   File "/data00/tjx/quant/test.py", line 42, in main
[rank0]:     quant_service.run_pipeline(
[rank0]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 74, in run_pipeline
[rank0]:     self.processors["load"].process(** load_params)
[rank0]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 113, in process
[rank0]:     self.pre_process(model_path, quant_config_path)
[rank0]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 158, in pre_process
[rank0]:     self._parse_model_config(model_path)
[rank0]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 144, in _parse_model_config
[rank0]:     original_config_path = os.path.join(self.model_path, "config.json")
[rank0]:                                         ^^^^^^^^^^^^^^^
[rank0]: AttributeError: 'LoadProcessor' object has no attribute 'model_path'
[Rank 2] 分布式进程组初始化完成，绑定设备: cuda:2
量化流程执行失败: 'LoadProcessor' object has no attribute 'model_path'
[Rank 3] 分布式进程组初始化完成，绑定设备: cuda:3
[Rank 1] 分布式进程组初始化完成，绑定设备: cuda:1
量化流程执行失败: 'LoadProcessor' object has no attribute 'model_path'
量化流程执行失败: 'LoadProcessor' object has no attribute 'model_path'[rank2]: Traceback (most recent call last):
[rank2]:   File "/data00/tjx/quant/test.py", line 53, in <module>
[rank2]:     main()
[rank2]:   File "/data00/tjx/quant/test.py", line 42, in main
[rank2]:     quant_service.run_pipeline(
[rank2]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 74, in run_pipeline
[rank2]:     self.processors["load"].process(** load_params)
[rank2]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 113, in process
[rank2]:     self.pre_process(model_path, quant_config_path)
[rank2]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 158, in pre_process
[rank2]:     self._parse_model_config(model_path)
[rank2]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 144, in _parse_model_config
[rank2]:     original_config_path = os.path.join(self.model_path, "config.json")
[rank2]:                                         ^^^^^^^^^^^^^^^
[rank2]: AttributeError: 'LoadProcessor' object has no attribute 'model_path'

[rank1]: Traceback (most recent call last):
[rank1]:   File "/data00/tjx/quant/test.py", line 53, in <module>
[rank1]:     main()
[rank1]:   File "/data00/tjx/quant/test.py", line 42, in main
[rank1]:     quant_service.run_pipeline(
[rank1]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 74, in run_pipeline
[rank1]:     self.processors["load"].process(** load_params)
[rank1]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 113, in process
[rank1]:     self.pre_process(model_path, quant_config_path)
[rank1]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 158, in pre_process
[rank1]:     self._parse_model_config(model_path)
[rank1]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 144, in _parse_model_config
[rank1]:     original_config_path = os.path.join(self.model_path, "config.json")
[rank1]:                                         ^^^^^^^^^^^^^^^
[rank1]: AttributeError: 'LoadProcessor' object has no attribute 'model_path'
[rank3]: Traceback (most recent call last):
[rank3]:   File "/data00/tjx/quant/test.py", line 53, in <module>
[rank3]:     main()
[rank3]:   File "/data00/tjx/quant/test.py", line 42, in main
[rank3]:     quant_service.run_pipeline(
[rank3]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 74, in run_pipeline
[rank3]:     self.processors["load"].process(** load_params)
[rank3]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 113, in process
[rank3]:     self.pre_process(model_path, quant_config_path)
[rank3]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 158, in pre_process
[rank3]:     self._parse_model_config(model_path)
[rank3]:   File "/data00/tjx/quant/quant_service/quant_service.py", line 144, in _parse_model_config
[rank3]:     original_config_path = os.path.join(self.model_path, "config.json")
[rank3]:                                         ^^^^^^^^^^^^^^^
[rank3]: AttributeError: 'LoadProcessor' object has no attribute 'model_path'
[Rank 3] 已关闭分布式进程组
[Rank 7] 已关闭分布式进程组
[Rank 5] 已关闭分布式进程组
[Rank 0] 已关闭分布式进程组
W0909 08:05:56.956000 2526692 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2526783 closing signal SIGTERM
W0909 08:05:56.956000 2526692 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2526784 closing signal SIGTERM
W0909 08:05:56.957000 2526692 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2526785 closing signal SIGTERM
W0909 08:05:56.957000 2526692 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2526787 closing signal SIGTERM
W0909 08:05:56.958000 2526692 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2526788 closing signal SIGTERM
W0909 08:05:56.958000 2526692 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2526789 closing signal SIGTERM
W0909 08:05:56.958000 2526692 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2526790 closing signal SIGTERM
E0909 08:05:57.450000 2526692 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 3 (pid: 2526786) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 357, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/launcher/api.py", line 143, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/launcher/api.py", line 277, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-09-09_08:05:56
  host      : iv-ye3txm0nb4bw80cpdz48
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2526786)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
